name: Publish Package

on:
  push:
    tags:
      - 'v*'

permissions:
  id-token: write  # Required for OIDC
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          registry-url: 'https://registry.npmjs.org'

      - run: npm ci

      - name: Build Library
        run: npm run build

      - name: Run Tests
        run: npm run test -- --watch=false --browsers=ChromeHeadless

      - name: Publish to NPM
        run: npm publish ./dist/ngx-cookie-manager --provenance --access public
        # env:
        #   NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} # Fallback if OIDC fails, though Trusted Publisher should ignore this
